apiVersion: apps/v1
kind: Deployment
metadata:
  name: evergreen-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: evergreen-backend
  template:
    metadata:
      labels:
        app: evergreen-backend
    spec:
      containers:
        - name: evergreen-backend
          image: evergreen-backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/evergreen
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: evergreen-secret
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: evergreen-secret
                  key: POSTGRES_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: evergreen-secret
                  key: JWT_SECRET
            - name: SPRING_MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: evergreen-secret
                  key: MAIL_USERNAME
            - name: SPRING_MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: evergreen-secret
                  key: MAIL_PASSWORD
