apiVersion: v1
kind: Secret
metadata:
  name: evergreen-secret
type: Opaque
stringData:
  POSTGRES_USER: user
  POSTGRES_PASSWORD: password
  JWT_SECRET: wtkey
  MAIL_USERNAME: evergreendata.fajitasmaster@gmail.com
  MAIL_PASSWORD: jcbiekeambzfgabw